# Generated by Django 5.2.9 on 2026-08-01 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_team_leagues'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSquad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='squad', to='sports.team')),
            ],
        ),
    ]
