# Generated by Django 5.2.9 on 2026-08-02 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0005_playerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopScorer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topscorers', to='sports.league')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topscorers', to='sports.season')),
            ],
            options={
                'verbose_name': 'Top Scorer',
                'unique_together': {('league', 'season')},
            },
        ),
    ]
