# Generated by Django 5.2.9 on 2026-08-02 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0006_topscorer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStatList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_type', models.CharField(choices=[('topscorers', 'Top Scorers'), ('topassists', 'Top Assists'), ('topyellowcards', 'Top Yellow Cards'), ('topredcards', 'Top Red Cards')], max_length=20)),
                ('data', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stat_lists', to='sports.league')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stat_lists', to='sports.season')),
            ],
            options={
                'verbose_name': 'Player Stat List',
                'unique_together': {('league', 'season', 'stat_type')},
            },
        ),
        migrations.DeleteModel(
            name='TopScorer',
        ),
    ]
