# Generated by Django 5.2.9 on 2026-08-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0008_venue_address_venue_capacity_venue_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_popular',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
