# Generated by Django 5.2.9 on 2026-01-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='otp',
            field=models.CharField(max_length=6),
        ),
    ]
