# Generated by Django 5.2.9 on 2026-08-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_team_leagues'),
        ('users', '0004_fanprofile_last_inbox_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favorite_leagues', models.ManyToManyField(blank=True, related_name='guest_favorites', to='sports.league')),
                ('favorite_teams', models.ManyToManyField(blank=True, related_name='guest_favorites', to='sports.team')),
            ],
        ),
    ]
