# Generated by Django 5.2.9 on 2026-08-03 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_guestfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanprofile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('tr', 'Turkish')], default='en', max_length=10),
        ),
    ]
