# Generated by Django 5.2.9 on 2026-08-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0009_team_is_popular'),
        ('users', '0006_fanprofile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanprofile',
            name='favorite_fixtures',
            field=models.ManyToManyField(blank=True, related_name='favorited_by_fans', to='sports.fixture'),
        ),
        migrations.AddField(
            model_name='guestfavorite',
            name='favorite_fixtures',
            field=models.ManyToManyField(blank=True, related_name='guest_favorites', to='sports.fixture'),
        ),
    ]
