# Generated by Django 5.2.9 on 2026-08-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_fanprofile_favorite_fixtures_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestfavorite',
            name='last_inbox_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
