# Generated by Django 5.2.9 on 2026-08-15 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_userdevice_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userhiddennotification',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userhiddennotification',
            name='guest_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userhiddennotification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hidden_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='userhiddennotification',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'notification'), name='unique_user_notification_hide'),
        ),
        migrations.AddConstraint(
            model_name='userhiddennotification',
            constraint=models.UniqueConstraint(condition=models.Q(('guest_id__isnull', False)), fields=('guest_id', 'notification'), name='unique_guest_notification_hide'),
        ),
    ]
